import { Document, Page, Text, View, Image } from "@react-pdf/renderer";

import { pdfStyles as s } from "./styles";
import type { InvoicePdfData } from "./types";

export function InvoicePdf({ data }: { data: InvoicePdfData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.row}>
          <View>
            {data.orgLogoUrl ? (
              <Image src={data.orgLogoUrl} style={{ width: 48, height: 48, marginBottom: 8 }} />
            ) : null}
            <Text style={s.muted}>Bill To</Text>
            <Text style={{ fontSize: 14, fontWeight: 700 }}>{data.orgName}</Text>
          </View>
          <View style={{ textAlign: "right" }}>
            <Text style={s.h1}>Invoice</Text>
            <Text style={s.muted}>{data.documentNumber}</Text>
            <Text style={s.muted}>Issued: {data.issueDate}</Text>
            <Text style={s.muted}>Due: {data.dueDate}</Text>
          </View>
        </View>

        <View style={s.line} />

        <Text style={s.h2}>From</Text>
        <Text style={{ fontWeight: 700 }}>{data.contractorName}</Text>
        {data.contractorAddress ? (
          <Text style={s.muted}>{data.contractorAddress}</Text>
        ) : null}
        {data.taxId ? <Text style={s.muted}>Tax ID: {data.taxId}</Text> : null}

        <View style={s.line} />

        <View style={s.tableHeader}>
          <Text style={s.colWide}>Description</Text>
          <Text style={s.col}>Hours</Text>
          <Text style={s.col}>Rate</Text>
          <Text style={s.col}>Amount</Text>
        </View>
        <View style={s.tableRow}>
          <Text style={s.colWide}>
            Professional services — {data.periodStart} to {data.periodEnd}
          </Text>
          <Text style={s.col}>{data.totalHours.toFixed(2)}</Text>
          <Text style={s.col}>{data.rateLabel}</Text>
          <Text style={s.col}>{data.subtotalLabel}</Text>
        </View>

        <View style={s.totalRow}>
          <Text>Subtotal: {data.subtotalLabel}</Text>
        </View>
        {data.gstEnabled && (
          <View style={s.totalRow}>
            <Text>
              GST ({(data.gstRate * 100).toFixed(0)}%): {data.gstLabel}
            </Text>
          </View>
        )}
        <View style={s.totalRow}>
          <Text style={{ fontWeight: 700 }}>Total: {data.totalLabel}</Text>
        </View>

        <View style={s.line} />
        <Text style={s.h2}>Bank details</Text>
        {data.bankName ? <Text>{data.bankName}</Text> : null}
        {data.accountName ? <Text>{data.accountName}</Text> : null}
        {data.accountNumber ? <Text>Account: {data.accountNumber}</Text> : null}
        {data.bsbSwift ? <Text>BSB / SWIFT: {data.bsbSwift}</Text> : null}
        <Text style={[s.muted, { marginTop: 8 }]}>
          Payment terms: {data.paymentTermsDays} days
        </Text>

        <Text style={s.footer}>
          {data.documentNumber} · Generated by Cadence
        </Text>
      </Page>
    </Document>
  );
}
