import { Document, Page, Text, View, Image } from "@react-pdf/renderer";

import { pdfStyles as s } from "./styles";
import type { PayAdvicePdfData } from "./types";

export function PayAdvicePdf({ data }: { data: PayAdvicePdfData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.row}>
          <View>
            {data.orgLogoUrl ? (
              <Image src={data.orgLogoUrl} style={{ width: 48, height: 48, marginBottom: 8 }} />
            ) : null}
            <Text style={{ fontSize: 14, fontWeight: 700 }}>{data.orgName}</Text>
          </View>
          <View style={{ textAlign: "right" }}>
            <Text style={s.muted}>{data.documentNumber}</Text>
            <Text style={s.muted}>{data.issueDate}</Text>
          </View>
        </View>

        <View style={s.line} />
        <Text style={s.h1}>Pay Advice</Text>

        <Text style={s.h2}>Employee</Text>
        <Text>{data.employeeName}</Text>
        <Text style={s.muted}>{data.employeeEmail}</Text>
        <Text style={s.muted}>{data.employeeRole}</Text>
        <Text style={s.muted}>
          Period: {data.periodStart} – {data.periodEnd}
        </Text>

        <View style={s.line} />

        <View style={s.tableHeader}>
          <Text style={s.colWide}>Description</Text>
          <Text style={s.col}>Hours</Text>
          <Text style={s.col}>Rate</Text>
          <Text style={s.col}>Amount</Text>
        </View>
        <View style={s.tableRow}>
          <Text style={s.colWide}>Timesheet period</Text>
          <Text style={s.col}>{data.totalHours.toFixed(2)}</Text>
          <Text style={s.col}>{data.rateLabel}</Text>
          <Text style={s.col}>{data.subtotalLabel}</Text>
        </View>

        <View style={s.totalRow}>
          <Text>Subtotal: {data.subtotalLabel}</Text>
        </View>
        {data.gstEnabled && (
          <View style={s.totalRow}>
            <Text>
              GST ({(data.gstRate * 100).toFixed(0)}%): {data.gstLabel}
            </Text>
          </View>
        )}
        <View style={s.totalRow}>
          <Text style={{ fontWeight: 700 }}>Total: {data.totalLabel}</Text>
        </View>

        <View style={s.line} />
        <Text style={s.muted}>
          Approved by {data.approvedBy} on {data.approvedAt}
        </Text>

        <Text style={s.footer}>
          {data.documentNumber} · Generated by Cadence
        </Text>
      </Page>
    </Document>
  );
}
